# Copyright (c) 2020 Leon Kuchenbecker <leon.kuchenbecker@uni-tuebingen.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Global rules including conversion of tool specific output to MultiHLA
# standard output
include: 'rules/multihla.smk'

# UCSC human genome download and alt contig filter
include: 'rules/ucsc_hg_download.smk'

# Comparison to ground truth alleles
include: 'rules/compare.smk'

# Adapter trimming
include: 'rules/trim.smk'

# Read mapping
include: 'rules/map/bwa.smk'
include: 'rules/map/star.smk'

# Tool: HLA VBSeq
include: 'rules/hla_vbseq.smk'

# Tool: xHLA
include: 'rules/xhla.smk'

# Tool: HLA-LA
include: 'rules/hla_la.smk'

# Tool: OptiType
include: 'rules/optitype.smk'

# Tool: arcasHLA
include: 'rules/arcasHLA.smk'
